services:
  db:
    image: postgres:15-alpine
    container_name: smart-url-db
    restart: always
    environment:
      POSTGRES_DB: smart_url_db
      POSTGRES_USER: smart_user
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: smart-url-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smart_url_db
      SPRING_DATASOURCE_USERNAME: smart_user
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      SMARTURL_BASE_URL: http://localhost:8080
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: smart-url-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
