# spring.application.name=smart-url-shortener

# # Database Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/smart_url_db?createDatabaseIfNotExist=true
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # JPA Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# # JWT Configuration
# # Generate a secret key: openssl rand -base64 32
# smarturl.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# smarturl.app.jwtExpirationMs=86400000

# # Server Configuration
# server.port=8080

# # Logging
# logging.level.org.springframework.security=DEBUG


spring.application.name=smart-url-shortener

# 1. Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_url_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. JWT & Server
smarturl.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
smarturl.app.jwtExpirationMs=86400000
server.port=8080
smarturl.base-url=http://localhost:8080
